name: lsml2_final
channels:
  - defaults
dependencies:
- python=3.8.2
- pip
- pip:
  - torch==1.9.0
  - torch==1.9.0
  - nltk==3.6.2
  - beautifulsoup4==4.9.3
  - pandas==1.3.2
  - numpy==1.21.2
  - mlflow==1.20.2
  - scikit-learn==0.24.2